apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: early-wildcat-go 
  janus-idp.io/tekton: early-wildcat-go
  backstage.io/kubernetes-id: early-wildcat-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: early-wildcat-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  